### ISSUE TITLE
Wildcard on intermediate objects isn't working.

### ISSUE THREAD

**Issue by Skarlso** [Skarlso/jsonpathv2#10]
```ruby
  def test_wildcard_asterisk_supported_on_intermediate_elements
    assert_equal ['red'], JsonPath.new("$.store.*.color").on(@object)
  end
```

This should return `red` but isn't at the moment. /cc @fleck

**Comment by Skarlso** [comment]
This is proving to be difficult to implement in the current structure.

**Comment by Skarlso** [comment]
The whole structure is broken this way. For example this doesn't work either:

```ruby
  def test_wildcard_on_intermediary_element_v5
    assert_equal [1, 1], JsonPath.on({ 'a' => { 'b' => { 'd' => { 'c' => 1, 'c' => 1 } } } }, '$.a..*.c')
  end
```

And neither is anything which is supposed to be getting back multiple results. It will prove difficult to say the least to fix this in the current recursive structure.

**Comment by Skarlso** [comment]
So I've been hacking on this for a while than my Baby was born, and I didn't have time to continue. But it's not forgotten, and certainly not something I don't want to fix.

**Comment by Skarlso** [comment]
FIXED!!

**Comment by fleck** [comment]
Thanks for the fix and congratulations on the baby!

**Comment by Skarlso** [comment]
@fleck Thanks man! :)
